# ?????? application.properties
# spring.application.name=m5-level-04
# server.port=9090
# feature.greeting.enabled=true
# spring.autoconfigure.exclude=org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration
# debug=false

# ?????? application.yaml
spring:
  application:
    name: m5-level-04

server:
  port: 9191

feature:
  greeting:
    enabled: true

