spring.application.name=m5-level-15

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (доступна по http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# GraphQL: эндпоинт /graphql (по умолчанию)
# GraphiQL: браузерная IDE для тестирования запросов (http://localhost:8080/graphiql)
spring.graphql.graphiql.enabled=true
