CREATE TABLE IF NOT EXISTS AUTHORS (
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    bio  VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS BOOKS (
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    title     VARCHAR(200) NOT NULL,
    author_id BIGINT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES AUTHORS (id)
);
